backup:
  from: /home/pathao/Pictures
  to: /home/pathao/mybackup2
  key: 1234

init:
  path: /home/pathao/mybackup2
  key: 1234

restore:
  from: /home/pathao/mybackup2
  to: /home/pathao/restored
  key: 1234

snapshots:
  path: /home/pathao/mybackup2
  key: 1234

