version: '3.8'

services:
  app-db:
    container_name: user-access-db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
  app:
    container_name: user-access
    build:
      dockerfile: DockerfileServer
    ports:
      - "8085:8085"
    depends_on:
      - app-db
  redis:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379
volumes:
  dbdata:
  data: